### ISSUE TITLE
Minimize cashflow among friends

### ISSUE THREAD

**Issue by webdev3211** [UtkarshBehre/InterviewQuestionsPracticeInJava#1]
Can you add comments to your code ??
I know C++ but due to your code written in Java I m not able to understand it clearly
If you add comments to your code it would be more simpler to understand
<a href="https://disq.us/url?url=https%3A%2F%2Fgithub.com%2FUtkarshBehre%2FInterviewQuestionsPracticeInJava%2Fblob%2Fmaster%2Fsrc%2FpopularQuestionSet%2FGraphSplitwiseSimplify.java%3AMQDRyWEaDVeeLetH6_mCMwJO-Zw&cuid=2480709">Link to your code</a>

Thank you

**Comment by UtkarshBehre** [comment]
I have added the comments now (commit 56e23be5edb9c1ededf845b2fae842e3b70473b4), please let me know if you still have any doubts in the solution and I will try to clarify the same.
